runtime: nodejs12

inbound_services:
- warmup

handlers:
- url: /ping
  script: auto
  secure: always
  redirect_http_response_code: 301

- url: /_ah/warmup
  script: auto
  secure: always
  redirect_http_response_code: 301

- url: /
  static_files: index.html
  upload: index.html
  secure: always
  redirect_http_response_code: 301
